#!/usr/bin/env python3
"""Prepare a deploy of the static site.

Encodes the rules that took two outages to learn:

1. GitHub Pages serves /assets with max-age=14400, so any file whose CONTENT
   changes must also change NAME -- otherwise the CDN can serve a stale copy.
2. The entry bundle and the map chunk import each other, so they must move
   together under one tag. Moving only one lets the CDN pair files from two
   different deploys: React initialises twice and the page goes blank.
3. Previously published entry names are never deleted. They stay as
   self-resolving shims so browsers holding cached HTML still boot.
4. Subresource Integrity is recomputed for the entry and stylesheet so a
   tampered file (anywhere between origin and browser) refuses to execute.

Usage: python3 release.py
"""
import base64, glob, hashlib, os, re, sys

A = 'assets'

def sri(path):
    return 'sha384-' + base64.b64encode(
        hashlib.sha384(open(path, 'rb').read()).digest()).decode()

def main():
    html = open('index.html').read()
    entry_old = re.search(r'/assets/(index-[A-Za-z0-9]+\.js)', html).group(1)
    css = re.search(r'/assets/(index-[A-Za-z0-9]+\.css)', html).group(1)
    map_old = re.search(r'(AbuDhabiMap-[A-Za-z0-9]+\.js)',
                        open(f'{A}/{entry_old}').read()).group(1)

    n = 1 + max([int(m.group(1)) for f in glob.glob(f'{A}/index-b*.js')
                 for m in [re.match(r'index-b(\d+)\.js$', os.path.basename(f))] if m] or [0])
    tag = f'b{n}'
    entry_new, map_new = f'index-{tag}.js', f'AbuDhabiMap-{tag}.js'

    # move the pair together, rewriting their references to each other
    open(f'{A}/{entry_new}', 'w').write(open(f'{A}/{entry_old}').read().replace(map_old, map_new))
    open(f'{A}/{map_new}', 'w').write(open(f'{A}/{map_old}').read().replace(entry_old, entry_new))

    # retired names keep serving
    open(f'{A}/{map_old}', 'w').write(f"export * from './{map_new}';\n")
    shims = sorted({os.path.basename(p) for p in glob.glob(f'{A}/index-*.js')}
                   - {entry_new, css})
    shims = [s for s in shims if s != entry_new]
    guard = '|'.join(re.escape(s[:-3]) for s in shims)
    for s in shims:
        open(f'{A}/{s}', 'w').write(SHIM % (guard, entry_new))

    integrity_js, integrity_css = sri(f'{A}/{entry_new}'), sri(f'{A}/{css}')
    for f in ('index.html', '404.html'):
        s = open(f).read().replace(entry_old, entry_new)
        s = re.sub(r'(<script type="module")[^>]*?( src="/assets/index-[A-Za-z0-9]+\.js")[^>]*(></script>)',
                   rf'\1 crossorigin integrity="{integrity_js}"\2\3', s)
        s = re.sub(r'(<link rel="stylesheet")[^>]*?( href="/assets/index-[A-Za-z0-9]+\.css")[^>]*(>)',
                   rf'\1 crossorigin integrity="{integrity_css}"\2\3', s)
        open(f, 'w').write(s)

    print(f'tag {tag}: {entry_old} -> {entry_new}, {map_old} -> {map_new}')
    print(f'shims refreshed: {len(shims)}')
    print(f'integrity js  {integrity_js[:24]}...')
    print(f'integrity css {integrity_css[:24]}...')

SHIM = """/* Legacy entry for browsers holding cached HTML from an earlier build.
   Discovers the current bundle from a no-store fetch of index.html, so a
   CDN-cached copy of this file stays correct. Guarded so a shim can never
   import another shim. Regenerated by release.py -- do not hand-edit. */
(async () => {
  if (window.__phazaEntryLoaded) return;
  window.__phazaEntryLoaded = 1;
  const IS_SHIM = /(%s)\\.js$/;
  try {
    const html = await fetch('/?_cb=' + Date.now(), { cache: 'no-store' }).then((r) => r.text());
    const css = html.match(/\\/assets\\/index-[A-Za-z0-9]+\\.css/);
    if (css) {
      document.querySelectorAll('link[rel="stylesheet"]').forEach((l) => {
        if (/\\/assets\\/index-[A-Za-z0-9]+\\.css/.test(l.getAttribute('href') || '')) {
          l.removeAttribute('integrity');
          l.setAttribute('href', css[0]);
        }
      });
    }
    const js = html.match(/\\/assets\\/index-[A-Za-z0-9]+\\.js/);
    if (js && !IS_SHIM.test(js[0])) { await import(js[0]); return; }
  } catch {}
  await import('/assets/%s');
})();
"""

if __name__ == '__main__':
    main()
